<!-- Inline and dependency-free so the screen remains usable while external assets recover. -->
<style id="idas-boot-recovery-style">
html.idas-boot-pending body>*:not(#idas-boot-recovery-overlay){visibility:hidden!important}
#idas-boot-recovery-overlay{position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;background:#f5f6f7;color:#222;font-family:Arial,"Microsoft JhengHei",sans-serif;visibility:visible!important}
#idas-boot-recovery-overlay[hidden]{display:none!important}#idas-boot-recovery-card{width:min(520px,calc(100vw - 40px));box-sizing:border-box;padding:28px 34px;border:1px solid #d8dde2;border-radius:10px;background:#fff;box-shadow:0 4px 18px rgba(0,0,0,.12);text-align:center}
#idas-boot-recovery-spinner{width:44px;height:44px;margin:0 auto 18px;border:4px solid #d9dee3;border-top-color:#2878c8;border-radius:50%;animation:idas-boot-spin .9s linear infinite}#idas-boot-recovery-title{font-size:22px;font-weight:700;margin-bottom:10px}#idas-boot-recovery-message{font-size:15px;line-height:1.6;color:#555}#idas-boot-recovery-retry{display:none;margin:20px auto 0;padding:10px 24px;border:0;border-radius:6px;background:#2878c8;color:#fff;font-size:15px;cursor:pointer}@keyframes idas-boot-spin{to{transform:rotate(360deg)}}
</style>
<script>
(function(){'use strict';
var RK='idas_asset_recovery_count',SK='idas_startup_retry_count',MAX=1,DELAY=3000,failed=false,waiting=false,timer=null;
window.addEventListener('error',function(e){var t=e&&e.target;if(t&&(t.tagName==='LINK'||t.tagName==='SCRIPT'))failed=true;},true);
function tx(){var l='zh-tw';try{var m=document.cookie.match(/(?:^|; )language=([^;]*)/);l=m?decodeURIComponent(m[1]).toLowerCase():l;}catch(e){}if(l==='zh-cn')return['iDAS 正在启动','系统服务正在恢复，请稍候。','系统尚未完全就绪，请重新加载。','重新加载'];if(l==='en'||l==='en-us')return['iDAS is starting','System services are recovering. Please wait.','The system is not ready yet. Please reload.','Reload'];return['iDAS 正在啟動','系統服務正在恢復，請稍候。','系統尚未完全就緒，請重新載入。','重新載入'];}
function reload(){var p=location.href.split('#'),u=p.shift();u+=(u.indexOf('?')>=0?'&':'?')+'_idas_boot='+Date.now();location.replace(u+(p.length?'#'+p.join('#'):''));}
function overlay(message){var o=document.getElementById('idas-boot-recovery-overlay'),t=tx();if(!o&&document.body){o=document.createElement('div');o.id='idas-boot-recovery-overlay';o.innerHTML='<div id="idas-boot-recovery-card" role="status" aria-live="polite"><div id="idas-boot-recovery-spinner"></div><div id="idas-boot-recovery-title"></div><div id="idas-boot-recovery-message"></div><button id="idas-boot-recovery-retry" type="button"></button></div>';document.body.appendChild(o);document.getElementById('idas-boot-recovery-title').textContent=t[0];var b=document.getElementById('idas-boot-recovery-retry');b.textContent=t[3];b.onclick=function(){try{sessionStorage.removeItem(RK);sessionStorage.removeItem(SK);}catch(e){}reload();};}if(o){o.hidden=false;document.getElementById('idas-boot-recovery-message').textContent=message||t[1];}document.documentElement.classList.add('idas-boot-pending');}
function hide(){var o=document.getElementById('idas-boot-recovery-overlay');if(o)o.hidden=true;document.documentElement.classList.remove('idas-boot-pending');try{sessionStorage.removeItem(RK);sessionStorage.removeItem(SK);}catch(e){}}
function sheetReady(x){if(x.disabled)return true;if(!x.sheet)return false;try{void x.sheet.cssRules;return true;}catch(e){return true;}}
function layoutReady(){var b=document.querySelector('#bnt1.button');if(!b)return true;var s=getComputedStyle(b),h=parseFloat(s.height||'0'),fs=parseFloat(s.fontSize||'0'),bg=s.backgroundColor||'';return h>=40&&fs>=17&&s.display==='inline-block'&&bg!=='rgba(0, 0, 0, 0)'&&bg!=='transparent';}
function healthy(){var a=[].slice.call(document.querySelectorAll('link[rel="stylesheet"]'));return !failed&&document.readyState==='complete'&&a.every(sheetReady)&&layoutReady()&&typeof window.jQuery==='function'&&typeof window.alertify!=='undefined';}
function check(){if(healthy()){hide();return;}overlay();var n=0;try{n=parseInt(sessionStorage.getItem(RK)||'0',10)||0;}catch(e){}if(n>=MAX){var m=document.getElementById('idas-boot-recovery-message'),b=document.getElementById('idas-boot-recovery-retry');if(m)m.textContent=tx()[2];if(b)b.style.display='block';return;}try{sessionStorage.setItem(RK,String(n+1));}catch(e){}setTimeout(reload,DELAY);}
function probe(){if(!waiting)return;var u=new URL(location.href);u.searchParams.set('_idas_web_probe',String(Date.now()));fetch(u.toString(),{cache:'no-store',credentials:'same-origin'}).then(function(r){if(!r.ok)throw 0;waiting=false;if(healthy())hide();else reload();}).catch(function(){timer=setTimeout(probe,DELAY);});}
window.IDASBootRecovery={show:overlay,hide:hide,check:check,waitForBackend:function(m){overlay(m);waiting=true;if(timer)clearTimeout(timer);probe();}};
window.addEventListener('load',function(){setTimeout(function(){if(failed)check();else hide();},700);},{once:true});setTimeout(function(){if(failed)check();},8000);
})();
</script>
